import type { PortfolioContent } from "./types";

export const FALLBACK_CONTENT: PortfolioContent = {
  settings: {
    portfolioType: "musician",
    footerEffect: "soul",
    artistName: "Franky Fugazi",
    displayFont: "playfair-display",
    bodyFont: "inter",
    uiFont: "manrope",
    tagline: "Music / Photos / Illustration",
    description:
      "Official portfolio for Franky Fugazi - music, video, biography, and booking.",
    location: "Amsterdam, The Netherlands",
    spotifyArtistUrl:
      "https://open.spotify.com/artist/3j6ZTLub4b9G6huqfRDIIM",
    spotifyEmbedUrl:
      "https://open.spotify.com/embed/artist/3j6ZTLub4b9G6huqfRDIIM?theme=0",
    contactBlurb: "Use the form for direct booking and inquiries.",
  },
  heroes: {
    home: {
      title: "FRANKY FUGAZI",
      subtitle: "MUSIC / PHOTOS / ILLUSTRATION",
      ctaLabel: "",
      ctaHref: "#home-about",
      backgroundSrc: "/images/hero.jpg",
      posterSrc: "",
      mediaType: "image",
    },
    bio: {
      title: "BIOGRAPHY",
      subtitle: "BIO",
      ctaLabel: "READ",
      ctaHref: "#bio",
      backgroundSrc: "/images/bio-hero.jpg",
      posterSrc: "",
      mediaType: "image",
    },
    gallery: {
      title: "GALLERY",
      subtitle: "HEADSHOTS",
      ctaLabel: "VIEW",
      ctaHref: "#gallery",
      backgroundSrc: "/images/bio-music.jpg",
      posterSrc: "",
      mediaType: "image",
    },
    music: {
      title: "MUSIC",
      subtitle: "LISTEN",
      ctaLabel: "SCROLL",
      ctaHref: "#music",
      backgroundSrc: "/images/music-hero.jpg",
      posterSrc: "",
      mediaType: "image",
    },
    video: {
      title: "VIDEOS",
      subtitle: "WATCH",
      ctaLabel: "SCROLL",
      ctaHref: "#videos",
      backgroundSrc: "/media/hero-loop.mp4",
      posterSrc: "",
      mediaType: "video",
    },
    booking: {
      title: "BOOKING",
      subtitle: "CONTACT",
      ctaLabel: "WRITE",
      ctaHref: "#form",
      backgroundSrc: "/images/booking-hero.jpg",
      posterSrc: "",
      mediaType: "image",
    },
  },
  homeUpdates: [
    {
      id: "latest-track",
      text: "My latest track is out now",
      linkLabel: "Listen here",
      href: "https://open.spotify.com/artist/3j6ZTLub4b9G6huqfRDIIM",
      avatarSrc: "/images/avatar-1.jpg",
    },
    {
      id: "atmospheric-productions",
      text: "Known for atmospheric and melodic productions.",
      avatarSrc: "/images/avatar-2.jpg",
    },
    {
      id: "sound-blend",
      text: "Blends indie, rock, and progressive sounds.",
      avatarSrc: "/images/avatar-3.jpg",
    },
    {
      id: "worldwide-events",
      text: "Plays at clubs and events worldwide.",
      avatarSrc: "/images/avatar-4.jpg",
    },
  ],
  homePresentation: {
    updatesHeading: "LATEST UPDATES",
    updatesImageSrc: "/images/updates.jpg",
    updatesImageAlt: "Latest updates",
    updatesCtaLabel: "VIEW GALLERY",
    updatesCtaHref: "/gallery",
    featureTitle: "THE INTERLUDE",
    featureBody:
      "Between the frames, the work keeps moving — a quiet study of process, presence, and motion.",
    featureCtaLabel: "WATCH SHOWREEL",
    featureCtaHref: "/video",
    featureImageSrc: "/images/video.jpg",
    featureImageAlt: "Showreel preview",
    featureVideoSrc: "",
    featurePosterSrc: "",
    storyTitle: "ARTIST FREELANCER LIFE",
    storyBody:
      "Stay curious, protect the spark, and let the work speak before the noise.",
    storyCtaLabel: "VIEW GALLERY",
    storyCtaHref: "/gallery",
    storyImage1Src: "",
    storyImage1Title: "ARTIST FREELANCER LIFE",
    storyImage1Body:
      "Stay curious, protect the spark, and let the work speak before the noise.",
    storyImage2Src: "",
    storyImage2Title: "FOLLOW THE INSTINCT",
    storyImage2Body:
      "Preparation creates the freedom to respond truthfully when the moment changes.",
    storyImage3Src: "",
    storyImage3Title: "STAY PRESENT",
    storyImage3Body:
      "Every frame asks for attention — listen closely, then let the character lead.",
    storyImage4Src: "",
    storyImage4Title: "KEEP THE SPARK",
    storyImage4Body:
      "Carry curiosity from one set to the next, and leave room for the unexpected.",
  },
  aboutHome: {
    heading: "ABOUT",
    body: "Guitarist with roots in England, now based in Amsterdam. I craft moody yet energetic indie rock - shimmering guitars, raw emotion, and melodies that linger long after the last chord fades. Come to a show and you will get a cinematic ride without unnecessary words - just sound, atmosphere, and honest intensity.",
    ctaLabel: "Find Out More",
    ctaHref: "/bio",
    imageSrc: "/images/about.jpg",
    imageAlt: "Artist portrait on stage",
  },
  socialLinks: [
    {
      id: "spotify",
      label: "Spotify",
      platform: "spotify",
      href: "https://open.spotify.com/artist/3j6ZTLub4b9G6huqfRDIIM",
      iconKey: "spotify",
    },
    {
      id: "soundcloud",
      label: "SoundCloud",
      platform: "soundcloud",
      href: "https://soundcloud.com",
      iconKey: "soundcloud",
    },
    {
      id: "instagram",
      label: "Instagram",
      platform: "instagram",
      href: "https://instagram.com",
      iconKey: "instagram",
    },
    {
      id: "youtube",
      label: "YouTube",
      platform: "youtube",
      href: "https://youtube.com",
      iconKey: "youtube",
    },
    {
      id: "bandcamp",
      label: "Bandcamp",
      platform: "bandcamp",
      href: "https://bandcamp.com",
      iconKey: "bandcamp",
    },
    {
      id: "apple-music",
      label: "Apple Music",
      platform: "apple",
      href: "https://music.apple.com",
      iconKey: "apple",
    },
  ],
  musicPlatforms: [
    {
      id: "beatport",
      title: "BEATPORT",
      label: "",
      href: "https://beatport.com",
      iconKey: "beatport",
      imageSrc: "/images/music-1.jpg",
    },
    {
      id: "spotify",
      title: "SPOTIFY",
      label: "",
      href: "https://open.spotify.com/artist/3j6ZTLub4b9G6huqfRDIIM",
      iconKey: "spotify",
      imageSrc: "/images/music-2.jpg",
    },
    {
      id: "soundcloud",
      title: "SOUNDCLOUD",
      label: "",
      href: "https://soundcloud.com",
      iconKey: "soundcloud",
      imageSrc: "/images/music-3.jpg",
    },
    {
      id: "apple-music",
      title: "APPLE MUSIC",
      label: "",
      href: "https://music.apple.com",
      iconKey: "apple",
      imageSrc: "/images/music-4.jpg",
    },
  ],
  soundcloudTracks: [
    {
      id: "mix-01",
      title: "",
      embedUrl: "https://api.soundcloud.com/tracks/soundcloud:tracks:247188263",
    },
    {
      id: "mix-02",
      title: "",
      embedUrl: "https://api.soundcloud.com/tracks/soundcloud:tracks:2114365833",
    },
    {
      id: "mix-03",
      title: "",
      embedUrl: "https://api.soundcloud.com/tracks/soundcloud:tracks:2189419043",
    },
    {
      id: "mix-04",
      title: "",
      embedUrl: "https://api.soundcloud.com/tracks/soundcloud:tracks:2159226369",
    },
    {
      id: "mix-05",
      title: "",
      embedUrl: "https://api.soundcloud.com/tracks/soundcloud:tracks:2120089767",
    },
  ],
  bio: {
    topLabel: "",
    introText: "",
    caption: "Amsterdam / Producer / Singer",
    galleryImages: [
      { id: "portrait-01", src: "/images/bio.jpg", alt: "Portrait 01" },
      { id: "portrait-02", src: "/images/bio-music.jpg", alt: "Portrait 02" },
      { id: "portrait-03", src: "/images/bio-music-1.jpg", alt: "Portrait 03" },
      { id: "portrait-04", src: "/images/bio-music-3.jpg", alt: "Portrait 04" },
    ],
    paragraphs: [
      {
        id: "bio-01",
        revealDelay: 140,
        body: "I create music that moves between shadow and glow - hypnotic rhythm, melodic tension, and textures that feel both intimate and massive. The sound is built to pull you in, not just to make noise. It is not about volume. It is about gravity.",
      },
      {
        id: "bio-02",
        revealDelay: 200,
        body: "Every track begins as a mood - sometimes fragile, sometimes raw. I collect fragments: field recordings, half-finished melodies, late-night synth accidents, conversations overheard in strange cities. They slowly start speaking to each other. What remains is never random.",
      },
      {
        id: "bio-03",
        revealDelay: 260,
        body: "My influences are intentionally messy: deeper electronic roots, emotional alternative edges, ambient spaces, and cultural fragments that show up when you least expect them. The result is always driven by narrative - even on a loud dancefloor.",
      },
      {
        id: "bio-04",
        revealDelay: 320,
        body: "Whether it is an intimate room or a big stage, the set is shaped like a story arc: slow tension, release, a little danger, and a clean landing. I am obsessed with pacing - how long can you hold a moment before it breaks into something bigger?",
      },
      {
        id: "bio-05",
        revealDelay: 380,
        body: "Over the years, the focus has stayed consistent: emotion, pace, atmosphere. I am not here to fill silence - I am here to build a world for a few minutes where people can actually feel something. A world that feels cinematic, but still human.",
      },
      {
        id: "bio-06",
        revealDelay: 440,
        body: "Production has become more minimal, but more precise. Fewer layers, more intention. I am interested in tension you can almost touch - the quiet before a drop, the air between two chords, the breath before impact.",
      },
      {
        id: "bio-07",
        revealDelay: 500,
        body: "Traveling shaped the sound in unexpected ways. England gave it depth. Amsterdam gave it urgency. Small rooms taught restraint. Big stages taught scale. Each city leaves a fingerprint.",
      },
      {
        id: "bio-08",
        revealDelay: 560,
        body: "I do not separate studio work from live performance. They feed each other constantly. A mistake in a live set can become the core of a future release. A studio experiment can redefine the energy of a night.",
      },
      {
        id: "bio-09",
        revealDelay: 620,
        body: "Right now the focus is on pushing production forward - more releases, collaborations, and live moments that feel like a short film you can dance to. Something immersive. Something that lingers after the lights come back on.",
      },
      {
        id: "bio-10",
        revealDelay: 680,
        body: "At the center of it all is one simple intention: create spaces where people feel suspended - just slightly outside of time. Not escaping reality. Just experiencing it differently.",
      },
    ],
  },
  galleryPresentation: {
    introEyebrow: "Artist gallery - selected frames",
    introTitle: "A visual archive with room to breathe.",
    interludeLabel: "The Interlude",
    interludeMeta: "Portfolio / In progress",
    interludeEyebrow: "A quiet study in motion",
    interludeTitle: "Between the frames, the work keeps moving.",
    interludeVideoSrc: "",
    interludePosterSrc: "",
    storyLabel: "Artist freelancer life",
    storyScrollLabel:
      "Stay curious, protect the spark, and let the work speak before the noise.",
  },
  galleryImages: [
    {
      id: "headshot-01",
      title: "Editorial Portrait",
      src: "/images/bio.jpg",
      alt: "Editorial actor portrait",
      caption: "Natural-light portrait suitable for casting and press.",
      category: "Headshot",
      isMosaic: true,
      isFreelanceStory: true,
      freelanceStoryOrder: 10,
    },
    {
      id: "headshot-02",
      title: "Studio Headshot",
      src: "/images/bio-music.jpg",
      alt: "Studio headshot portrait",
      caption: "Clean studio portrait for agencies and casting profiles.",
      category: "Headshot",
      isMosaic: true,
      isFreelanceStory: true,
      freelanceStoryOrder: 20,
    },
    {
      id: "portrait-03",
      title: "Character Portrait",
      src: "/images/bio-music-1.jpg",
      alt: "Character portrait",
      caption: "Mood-led portrait for editorial and role range context.",
      category: "Portrait",
      isMosaic: true,
      isFreelanceStory: true,
      freelanceStoryOrder: 30,
    },
    {
      id: "portrait-04",
      title: "Profile Still",
      src: "/images/bio-music-3.jpg",
      alt: "Profile still",
      caption: "Portfolio still with a cinematic profile angle.",
      category: "Still",
      isMosaic: true,
      isFreelanceStory: true,
      freelanceStoryOrder: 40,
    },
  ],
  videoPresentation: {
    sectionEyebrow: "SOCIAL",
    sectionTitle: "Showreel, scenes, and selected work",
    sectionBody:
      "Casting reels, performance clips, and screen work will appear here as the video library grows.",
    featuredLabel: "Featured showreel",
    featuredFallback: "Main reel for casting, agencies, and production teams.",
    libraryEyebrow: "Library",
    libraryTitle: "Scenes and Clips",
    emptyText: "Showreel and scenes are coming soon.",
  },
  videos: [],
  actorResume: {
    headline: "Screen and stage performer",
    summary:
      "Actor profile foundation for casting directors, agencies, and production teams. Replace this text with a focused performer summary, casting range, and recent work highlights.",
    location: "Amsterdam, The Netherlands",
    playingAge: "25-35",
    height: "",
    eyes: "",
    hair: "",
    languages: "English, Dutch",
    skills: "Improvisation, movement, stage combat, guitar",
    representation: "",
    resumeUrl: "",
  },
  actorCredits: [
    {
      id: "credit-film-01",
      creditType: "film",
      title: "Short Film Title",
      role: "Lead",
      production: "Independent Production",
      director: "Director Name",
      year: "2026",
      href: "",
    },
    {
      id: "credit-theatre-01",
      creditType: "theatre",
      title: "Stage Production",
      role: "Supporting",
      production: "Theatre Company",
      director: "Director Name",
      year: "2025",
      href: "",
    },
    {
      id: "credit-commercial-01",
      creditType: "commercial",
      title: "Commercial Campaign",
      role: "Principal",
      production: "Brand / Agency",
      director: "",
      year: "2025",
      href: "",
    },
  ],
};
